CREATE USER PG IDENTIFIED BY People;

GRANT CONNECT, RESOURCE TO PG;

CREATE TABLE CUSTOMER (
  C_ID NUMBER(5) PRIMARY KEY,
  C_NAME VARCHAR2(30),
  C_EMAIL VARCHAR2(30),
  C_PHONENUMBER NUMBER(10),
  C_DOB DATE,
  C_AGE NUMBER(3)
);

DELETE FROM CUSTOMER;

CREATE TABLE COMPLETES (
  T_ID NUMBER(5) PRIMARY KEY,
  T_DATE DATE,
  FEES NUMBER(5),
  AMOUNT NUMBER(10),
  C_ID NUMBER(5),
  CONSTRAINT CFK FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID)
);

CREATE TABLE TRANSACTION (
  T_ID NUMBER(5) PRIMARY KEY,
  T_DATE DATE,
  FEES NUMBER(5),
  AMOUNT NUMBER(10)
);

CREATE TABLE REQUEST_ROLLBACK (
  M_ID NUMBER(5) PRIMARY KEY,
  M_NAME VARCHAR2(30),
  M_EMAIL VARCHAR2(30),
  C_ID NUMBER(5),
  CONSTRAINT RFK FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID)
);

CREATE TABLE OPERATES (
  A_ID NUMBER(5) PRIMARY KEY,
  P_ID NUMBER(5),
  A_NAME VARCHAR2(30),
  A_EMAIL VARCHAR2(30),
  P_NAME VARCHAR2(30),
  T_ID NUMBER(5),
  CONSTRAINT OFK FOREIGN KEY (T_ID) REFERENCES TRANSACTION(T_ID)
);

CREATE TABLE USES (
  M_ID NUMBER(5) PRIMARY KEY,
  M_EMAIL VARCHAR(30),
  M_NAME VARCHAR(30),
  BUS_NAME VARCHAR(30),
  REG_DATE DATE,
  T_ID NUMBER(5),
  CONSTRAINT UFK FOREIGN KEY (T_ID) REFERENCES TRANSACTION(T_ID)
);

CREATE TABLE MERCHANTS(
  M_ID NUMBER(5) PRIMARY KEY,
  M_NAME VARCHAR(30),
  M_EMAIL VARCHAR(30),
  BUS_NAME VARCHAR(30),
  REG_DATE DATE
);

CREATE TABLE ADMIN(
  A_ID NUMBER(5) PRIMARY KEY,
  A_NAME VARCHAR(30),
  A_EMAIL VARCHAR(30)
);

CREATE TABLE CREATES(
  P_ID NUMBER(5) PRIMARY KEY,
  A_ID NUMBER(5),
  CONSTRAINT AFK FOREIGN KEY (A_ID) REFERENCES ADMIN(A_ID)
);

CREATE TABLE PAYMENT_METHODS(
  P_ID NUMBER(5) PRIMARY KEY,
  P_NAME VARCHAR(30)
);